
# dict1={'name':'Raju', 'marks':56}
# a=input("enter the name  ")
# if  a == dict1:
#     print("exist")
# else:
#     print("not exist")



a=(input("Enter your number:------"))
dict1={"name":"Raju", "marks":56}
# if dict1==a:
#     print("Exist")
# else:
#     print("not exist")






# i=0
# while i <2:
#     if dict1[i] in  a:
#        print("exist")
#     else:
#         print("not exist")
#     i=i+1